package com.vehicleman.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors (Ανοιχτό Θέμα)
val PrimaryLight = Color(0xFF006C4B) // Έντονο Πράσινο-Μπλε (για ενέργεια/κύριο στοιχείο)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF86F8C7)
val OnPrimaryContainerLight = Color(0xFF002114)
val SecondaryLight = Color(0xFF4D6357) // Γκριζοπράσινο (για δευτερεύοντα στοιχεία)
val OnSecondaryLight = Color(0xFFFFFFFF)
val TertiaryLight = Color(0xFF3B6373) // Μπλε-Γκρι (για πινελιές)
val OnTertiaryLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFF7FCF8)
val SurfaceLight = Color(0xFFF7FCF8)
val OnSurfaceLight = Color(0xFF191C1A)
val ErrorLight = Color(0xFFBA1A1A)

// Dark Theme Colors (Σκούρο Θέμα)
val PrimaryDark = Color(0xFF6AE6A9)
val OnPrimaryDark = Color(0xFF003825)
val PrimaryContainerDark = Color(0xFF005137)
val OnPrimaryContainerDark = Color(0xFF86F8C7)
val SecondaryDark = Color(0xFFBFCBC1)
val OnSecondaryDark = Color(0xFF1F352B)
val TertiaryDark = Color(0xFF8DCDEE)
val OnTertiaryDark = Color(0xFF003544)
val BackgroundDark = Color(0xFF191C1A)
val SurfaceDark = Color(0xFF191C1A)
val OnSurfaceDark = Color(0xFFE1E3DF)
val ErrorDark = Color(0xFFFFB4AB)
